dist: xenial

language: python

sudo: false

matrix:
  include:
    - python: 2.7
      env: TOX_ENV=py27-django111
    - python: 3.6
      env: TOX_ENV=py36-django111
    - python: 3.6
      env: TOX_ENV=py36-django20
    - python: 3.6
      env: TOX_ENV=py36-django21
    - python: 3.6
      env: TOX_ENV=py36-django22
    - python: 3.6
      env: TOX_ENV=py36-django30
    - python: 3.7
      env: TOX_ENV=py37-django20
    - python: 3.7
      env: TOX_ENV=py37-django21
    - python: 3.7
      env: TOX_ENV=py37-django22
    - python: 3.7
      env: TOX_ENV=py37-django30
    - python: 3.8
      env: TOX_ENV=py38-django22
    - python: 3.8
      env: TOX_ENV=py38-django30

addons:
  chrome: stable

install:
  - travis_retry pip install -U tox-travis
  - wget -N http://chromedriver.storage.googleapis.com/70.0.3538.16/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - export PATH=$PATH:/usr/local/bin/

script:
  - whereis google-chrome-stable
  - whereis chromedriver
  - tox -e $TOX_ENV
